### PR TITLE
+ Plugin File Check (WPSeek) + CarbonFields

### PR DESCRIPTION
**Pull request by mayeenulislam**

### CODE REVIEW

**Comment by franz-josef-kaiser** [comment]
@mayeenulislam description, please :)

**Comment by mayeenulislam** [comment]
I'm sorry, I forgot the description field. :(

* **Plugin File Check (WPSeek):** An automated tool for checking deprecated WordPress functions using WPSeek library, and can suggest the minimum WordPress Core version requirement for the plugin.
* **CarbonFields:** A custom field framework, useful for Post Meta, Theme Options, Taxonomy Term Meta, User Meta, Comment Meta, Widgets, Nav Menu fields, and Tabs. Open Source, and hosted in Github. Made by HTMLBurger.

**Comment by franz-josef-kaiser** [comment]
@mayeenulislam Two notes: 

1. You can edit your original description – always – with the "pencil" icon in the upper right corner
2. Can you please split out PRs to one link at a time? Else it's a bit tough to review commit history and accept/deny a PR

Thanks for the PR!

**Comment by mayeenulislam** [comment]
@franz-josef-kaiser I'm afraid, I got a bit busy now. Anyway, thanks for your tips.

**Pull request closed without merging**
