### PR TITLE
Added TypeRocket

### PR DESCRIPTION
**Pull request by twmbx**
Found this recently; I'm sure many would find it very useful.

**note**: they do mention ACF in the marketing blurb on the front page but it has nothing to do with ACF as far as I've seen in my use of it. That's just meant to illustrate its usefulness I believe.
link: https://typerocket.com/

### CODE REVIEW

**Comment by dnaber-de** [comment]
@twmbx 
Is it a framework for developing WordPress components or is it a bootstrap wrapper to run WordPress in conjunction with Composer as dependency manager?

**Comment by twmbx** [comment]
@dnaber-de It can do both. It can be used to wrap around a wordpress install and manage that install with composer but I've been using it inside themes or plugins to add functionality to work I already have on-line which I don't or can't start from scratch.

The possible ways of installing it are detailed here in the [docs](https://typerocket.com/docs/v3/#section-theme-installation)

**Comment by dnaber-de** [comment]
So I finally found some time to take a closer look on this. TypeRocket is quite complex and so is the documentation which is first of all a notable thing. It follows some interesting concepts and provides implementations for things like [DI-Container](https://typerocket.com/docs/v3/ioc-resolver/), [HTTP middleware](https://typerocket.com/docs/v3/middleware/) and [routing](https://typerocket.com/docs/v3/routes/), even some query builder with a [ORM like domain language](https://typerocket.com/docs/v3/models/#section-finding). But everything is part of one monolithic package and some of these concepts are not tied to WordPress and so it competes against other established PHP libraries.

My main point of criticism is, that I don't see how TypeRocket as a framework would help me to write my business logic in a more independent way. It offers no abstractions and so doesn't WordPress itself. Instead it advocates inheritance which would couple your code tightly to TypeRocket. So from this perspective I would replace one Framework (WordPress) with another for the sake just a different API with some MVC flavor.

TypeRocket core does not provide real (WP independend) unit tests. Today I would not rely on a framework (except on WordPress for historical reasons) that is not real unit tested for professional webwork.

Furthermore, instead of suggesting a usage with a generally accepted Composer workflow it advocates to bundle itself with a single Plugin or (even worse) a theme and [suggests to add logic to the `functions.php`](https://typerocket.com/docs/v3/taxonomies/#section-adding-a-taxonomy). That never was a good idea at all.

I respect the loot of work that was obviously put into TypeRocket and even more the extensive documentation. But I would not suggest to use it for the mentioned reasons.

Do you agree, @franz-josef-kaiser @GaryJones

**Review by dnaber-de — COMMENTED** [review]
RAAC (review as a comment): https://github.com/wecodemore/WordPress-Gear/pull/152#issuecomment-365286421

**Comment by twmbx** [comment]
well.. that's a lot of info. @dnaber-de maybe this repository needs a contributing.md ??

Also, yes, TypeRocket makes use of a lot of Laravel to do what it does (DI, routing, ORM etc), so does Themosis which is already listed in the index.md ( it's largely because of Themosis that I actually got interested in using wordpress again with client products, and having found TypeRocket I figured it might help someone else ). I'm not affiliated though so that's no skin off my back.

Again though; I figure this repository needs some published guidelines for contributions.

[EDIT]Also an actual description of the "philoshophy" behind the goal of the repository could be helpful. Otherwise the current description and encouragement to contribute on http://wpgear.org/ are honestly just misleading if you ask me.

**Pull request closed without merging**
